/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description System is healthy */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
        /** @description System is unhealthy */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List instances */
    get: {
      parameters: {
        query?: {
          /** @description Filter by channel (comma-separated) */
          channel?: string;
          /** @description Filter by status (active,inactive) */
          status?: string;
          limit?: number;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of instances */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Instance'][];
              meta?: components['schemas']['PaginationMeta'];
            };
          };
        };
      };
    };
    put?: never;
    /** Create instance */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            name: string;
            /** @enum {string} */
            channel: 'whatsapp-baileys' | 'whatsapp-cloud' | 'discord' | 'slack' | 'telegram';
            /** Format: uuid */
            agentProviderId?: string;
            /** @default default */
            agentId?: string;
          };
        };
      };
      responses: {
        /** @description Instance created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: components['schemas']['Instance'];
            };
          };
        };
        400: components['responses']['ValidationError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get instance */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Instance details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              data?: components['schemas']['Instance'];
            };
          };
        };
        404: components['responses']['NotFound'];
      };
    };
    put?: never;
    post?: never;
    /** Delete instance */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Instance deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components['responses']['NotFound'];
      };
    };
    options?: never;
    head?: never;
    /** Update instance */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': Record<string, never>;
        };
      };
      responses: {
        /** @description Instance updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        404: components['responses']['NotFound'];
      };
    };
    trace?: never;
  };
  '/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Send text message */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            instanceId: string;
            to: string;
            text: string;
            replyTo?: string;
          };
        };
      };
      responses: {
        /** @description Message sent */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        400: components['responses']['ValidationError'];
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/events': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List events */
    get: {
      parameters: {
        query?: {
          channel?: string;
          instanceId?: string;
          eventType?: string;
          since?: string;
          until?: string;
          search?: string;
          limit?: number;
          cursor?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of events */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Event'][];
              meta?: components['schemas']['PaginationMeta'];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/persons': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search persons */
    get: {
      parameters: {
        query: {
          search: string;
          limit?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of persons */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Person'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/access/rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List access rules */
    get: {
      parameters: {
        query?: {
          instanceId?: string;
          type?: 'allow' | 'deny';
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of access rules */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['AccessRule'][];
            };
          };
        };
      };
    };
    put?: never;
    /** Create access rule */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': {
            /** Format: uuid */
            instanceId?: string;
            /** @enum {string} */
            ruleType: 'allow' | 'deny';
            phonePattern?: string;
            platformUserId?: string;
            /** @default 0 */
            priority?: number;
          };
        };
      };
      responses: {
        /** @description Rule created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List settings */
    get: {
      parameters: {
        query?: {
          category?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Setting'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List providers */
    get: {
      parameters: {
        query?: {
          active?: boolean;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of providers */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              items?: components['schemas']['Provider'][];
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Error: {
      error?: {
        /** @description Error code */
        code: string;
        /** @description Error message */
        message: string;
        /** @description Additional error details */
        details?: Record<string, never>;
      };
    };
    Instance: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** @enum {string} */
      channel?: 'whatsapp-baileys' | 'whatsapp-cloud' | 'discord' | 'slack' | 'telegram';
      isActive?: boolean;
      profileName?: string | null;
      profilePicUrl?: string | null;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      updatedAt?: string;
    };
    Person: {
      /** Format: uuid */
      id?: string;
      displayName?: string | null;
      primaryPhone?: string | null;
      primaryEmail?: string | null;
      avatarUrl?: string | null;
      /** Format: date-time */
      createdAt?: string;
    };
    Event: {
      /** Format: uuid */
      id?: string;
      eventType?: string;
      channel?: string;
      contentType?: string | null;
      /** @enum {string} */
      direction?: 'inbound' | 'outbound';
      textContent?: string | null;
      /** Format: date-time */
      receivedAt?: string;
    };
    AccessRule: {
      /** Format: uuid */
      id?: string;
      /** @enum {string} */
      ruleType?: 'allow' | 'deny';
      /** Format: uuid */
      instanceId?: string | null;
      phonePattern?: string | null;
      platformUserId?: string | null;
      priority?: number;
      enabled?: boolean;
    };
    Setting: {
      /** Format: uuid */
      id?: string;
      key?: string;
      value?: string | null;
      /** @enum {string} */
      valueType?: 'string' | 'integer' | 'boolean' | 'json' | 'secret';
      category?: string | null;
      description?: string | null;
      isSecret?: boolean;
    };
    Provider: {
      /** Format: uuid */
      id?: string;
      name?: string;
      /** @enum {string} */
      schema?: 'openai' | 'anthropic' | 'agno' | 'custom';
      baseUrl?: string;
      isActive?: boolean;
      supportsStreaming?: boolean;
      supportsImages?: boolean;
      supportsAudio?: boolean;
    };
    HealthResponse: {
      /** @enum {string} */
      status?: 'healthy' | 'degraded' | 'unhealthy';
      version?: string;
      uptime?: number;
      /** Format: date-time */
      timestamp?: string;
      checks?: {
        database?: Record<string, never>;
        nats?: Record<string, never>;
      };
    };
    PaginationMeta: {
      hasMore?: boolean;
      cursor?: string | null;
      total?: number | null;
    };
  };
  responses: {
    /** @description Authentication required */
    Unauthorized: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
    /** @description Validation error */
    ValidationError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        'application/json': components['schemas']['Error'];
      };
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
