/**
 * Migration / runtime / auth-plane role split
 * (wish: omni-full-multitenancy, Group G3; ADR-0003, ADR-0004).
 *
 * WHAT IS ACTUALLY TRUE TODAY
 * ---------------------------
 * `packages/cli/src/lib/role-cutover.ts` provisions ONE non-superuser role and
 * then hands it everything: it `ALTER SCHEMA public OWNER TO` that role and
 * `GRANT ... CREATE ON DATABASE`, because migrate-on-boot runs on the very same
 * connection that later serves traffic. So the "scoped" runtime role today is
 * the schema owner, holds CREATE, and can therefore create, alter, and drop the
 * tables it is supposed to be constrained by. It is correctly `NOBYPASSRLS`,
 * but `NOBYPASSRLS` on a table OWNER means nothing until `FORCE ROW LEVEL
 * SECURITY` exists — and `FORCE` means nothing if the same role can
 * `ALTER TABLE ... NO FORCE`.
 *
 * ADR-0004 therefore does not describe a two-way split; it describes three
 * identities, plus the isolated auth plane of ADR-0003:
 *
 *   1. **provisioner** — a superuser, used at install time only, to run the
 *      statements in this file. It is not a role this module creates; it is the
 *      connection the operator hands to `applyTenancyRoles`.
 *   2. **DDL/owner** (`omni_ddl`) — owns the schema and every table, runs
 *      migrations, and is unavailable to the app process after boot.
 *   3. **runtime** (`omni_runtime`) — serves traffic. Owns nothing. No CREATE,
 *      no SET ROLE, NOBYPASSRLS, and no privilege at all on the control plane.
 *   4. **auth plane** (`omni_auth_plane_role`) — ADR-0003. SELECT-only, and the
 *      only identity that may read the credential index.
 *
 * SCOPE GATE
 * ----------
 * All of this is enforcement-mode only. Nothing here runs during a normal
 * install, a normal migration, or a normal boot; `role-cutover.ts` and its
 * documented `postgres:postgres` fallback are untouched for legacy deployments.
 * The fallback is removed only on the ENFORCED path — see `tenancy-startup.ts`.
 */

import { sql } from 'drizzle-orm';
import type { Database } from './client';
import {
  AUTH_PLANE_READABLE_TABLES,
  DEFAULT_ROLE_NAMES,
  QUALIFIED_AUTH_PLANE_FUNCTION,
  QUALIFIED_AUTH_PLANE_ROW_FUNCTION,
  QUALIFIED_TENANT_CONTEXT_FUNCTION,
  RUNTIME_DENIED_TABLES,
  type TenancyRoleNames,
} from './tenancy-rls';

const SAFE_IDENT = /^[a-z_][a-z0-9_]*$/;

function assertSafeIdent(label: string, value: string): void {
  if (!SAFE_IDENT.test(value) || value.length > 63) {
    throw new Error(`tenancy-roles: unsafe ${label} identifier: ${JSON.stringify(value)}`);
  }
}

/**
 * Passwords are generated by the caller and interpolated into `CREATE ROLE`,
 * which has no parameter binding. Restricting them to base64url alphabet is a
 * defense-in-depth check on a value we generate ourselves — the same stance
 * `role-cutover.ts` takes.
 */
function assertSafePassword(value: string): void {
  if (!/^[A-Za-z0-9_-]{16,200}$/.test(value)) {
    throw new Error('tenancy-roles: password must be 16-200 base64url characters');
  }
}

/** Attributes ADR-0004 requires of BOTH the runtime and the auth-plane role. */
const CONSTRAINED_ATTRIBUTES = 'NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS';

export interface TenancyRolePasswords {
  readonly ddl: string;
  readonly runtime: string;
  readonly authPlane: string;
}

/**
 * The `auth_credentials` index and its immediate joins. Only the auth-plane
 * role may SELECT these; the runtime role is denied outright, which is what
 * makes "tenant-scoped paths cannot enumerate the credential index" a privilege
 * fact rather than a code convention.
 */
export const AUTH_PLANE_TABLES: readonly string[] = [
  'auth_credentials',
  'platform_api_keys',
  'principals',
  'tenants',
  ...AUTH_PLANE_READABLE_TABLES,
];

/**
 * Every statement, in dependency order. Pure — returns SQL, executes nothing,
 * so the whole plan is reviewable and unit-testable without a server.
 */
export function roleProvisioningStatements(
  passwords: TenancyRolePasswords,
  roles: TenancyRoleNames = DEFAULT_ROLE_NAMES,
  database = 'omni',
  legacyRoles: readonly string[] = [],
): string[] {
  for (const [label, value] of Object.entries(roles)) assertSafeIdent(label, value);
  assertSafeIdent('database', database);
  for (const value of Object.values(passwords)) assertSafePassword(value);
  for (const value of legacyRoles) assertSafeIdent('legacy role', value);

  const { ddl, runtime, authPlane, authPlaneMarker } = roles;
  const statements: string[] = [];

  // --- 1. roles ------------------------------------------------------------
  // The DDL role is also NOBYPASSRLS: FORCE ROW LEVEL SECURITY binds the owner,
  // and an owner that could bypass would make the "owner cannot bypass" test a
  // tautology. The DDL role's power is schema authority, not data authority.
  const role = (name: string, extra: string): string => `DO $omni$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${name}') THEN
    EXECUTE ${quoteLiteral(`CREATE ROLE "${name}" ${extra}`)};
  ELSE
    EXECUTE ${quoteLiteral(`ALTER ROLE "${name}" ${extra}`)};
  END IF;
END
$omni$;`;

  statements.push(
    role(ddl, `WITH LOGIN PASSWORD '${passwords.ddl}' ${CONSTRAINED_ATTRIBUTES}`),
    role(runtime, `WITH LOGIN PASSWORD '${passwords.runtime}' ${CONSTRAINED_ATTRIBUTES}`),
    role(authPlane, `WITH LOGIN PASSWORD '${passwords.authPlane}' ${CONSTRAINED_ATTRIBUTES}`),
    role(authPlaneMarker, `WITH NOLOGIN ${CONSTRAINED_ATTRIBUTES}`),
    // The marker is what the two pre-context SELECT policies admit. Granting it
    // to the auth-plane role and to NOBODY else is the whole mechanism.
    `GRANT "${authPlaneMarker}" TO "${authPlane}";`,
    // Explicit: the runtime must never acquire the auth-plane identity. Guarded
    // by an existence check because REVOKE on a membership that was never
    // granted emits a WARNING on every run — noise that trains operators to
    // ignore warnings from this script.
    revokeMembership(authPlaneMarker, runtime),
    revokeMembership(authPlaneMarker, ddl),
  );

  // --- 2. ownership --------------------------------------------------------
  // Everything in `public` moves to the DDL role, including anything the legacy
  // scoped role owns today. Sequences and views move too, or the runtime would
  // keep incidental ALTER authority through a leftover ownership.
  statements.push(
    `ALTER SCHEMA public OWNER TO "${ddl}";`,
    `DO $omni$
DECLARE
  obj record;
BEGIN
  FOR obj IN
    SELECT c.relname, c.relkind
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relkind IN ('r', 'S', 'v', 'm', 'p')
      -- A serial/identity sequence is owned BY its table and follows the
      -- table's owner automatically; ALTER SEQUENCE ... OWNER TO on one is a
      -- hard error (0A000), not a no-op.
      AND NOT EXISTS (
        SELECT 1 FROM pg_depend d
        WHERE d.classid = 'pg_class'::regclass
          AND d.objid = c.oid
          AND d.deptype IN ('a', 'i')
      )
    ORDER BY CASE WHEN c.relkind IN ('r', 'p') THEN 0 ELSE 1 END
  LOOP
    IF obj.relkind IN ('r', 'p') THEN
      EXECUTE format('ALTER TABLE public.%I OWNER TO %I', obj.relname, '${ddl}');
    ELSIF obj.relkind = 'S' THEN
      EXECUTE format('ALTER SEQUENCE public.%I OWNER TO %I', obj.relname, '${ddl}');
    ELSIF obj.relkind = 'v' THEN
      EXECUTE format('ALTER VIEW public.%I OWNER TO %I', obj.relname, '${ddl}');
    ELSE
      EXECUTE format('ALTER MATERIALIZED VIEW public.%I OWNER TO %I', obj.relname, '${ddl}');
    END IF;
  END LOOP;
END
$omni$;`,
    // The migrator's bookkeeping schema. It exists only once drizzle has run,
    // so create-if-missing before taking ownership; the runtime role is granted
    // nothing here at all, which is why migration history is not rewritable
    // from the serving process.
    `CREATE SCHEMA IF NOT EXISTS drizzle AUTHORIZATION "${ddl}";`,
    `ALTER SCHEMA drizzle OWNER TO "${ddl}";`,
    `DO $omni$
DECLARE
  obj record;
BEGIN
  FOR obj IN
    SELECT c.relname
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'drizzle' AND c.relkind IN ('r', 'p')
  LOOP
    EXECUTE format('ALTER TABLE drizzle.%I OWNER TO %I', obj.relname, '${ddl}');
  END LOOP;
END
$omni$;`,
  );

  // --- 3. revoke the unsafe PUBLIC surface ---------------------------------
  // `CREATE ON SCHEMA public` is granted to PUBLIC by default on PostgreSQL 14
  // and older, and any role could create a table (or a function that shadows a
  // policy helper) there. `CONNECT`/`TEMPORARY` on the database likewise.
  statements.push(
    'REVOKE ALL ON SCHEMA public FROM PUBLIC;',
    `REVOKE ALL ON DATABASE "${database}" FROM PUBLIC;`,
    'REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC;',
    'REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC;',
  );

  // --- 4. runtime privileges ----------------------------------------------
  // USAGE, never CREATE. DML on everything, then a hard REVOKE of the control
  // plane — a denylist rather than an allowlist, so a NEW tenant table added
  // tomorrow is reachable by default and a new CONTROL-PLANE table is a
  // reviewed addition to `RUNTIME_DENIED_TABLES`.
  statements.push(
    `GRANT CONNECT, TEMPORARY ON DATABASE "${database}" TO "${runtime}";`,
    `GRANT CONNECT ON DATABASE "${database}" TO "${authPlane}";`,
    `GRANT CONNECT, TEMPORARY, CREATE ON DATABASE "${database}" TO "${ddl}";`,
    `GRANT USAGE ON SCHEMA public TO "${runtime}";`,
    `GRANT USAGE ON SCHEMA public TO "${authPlane}";`,
    `GRANT USAGE, CREATE ON SCHEMA public TO "${ddl}";`,
    `GRANT ALL ON SCHEMA drizzle TO "${ddl}";`,
    `GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "${runtime}";`,
    `GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO "${runtime}";`,
    `ALTER DEFAULT PRIVILEGES FOR ROLE "${ddl}" IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${runtime}";`,
    `ALTER DEFAULT PRIVILEGES FOR ROLE "${ddl}" IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO "${runtime}";`,
    // The policy helpers must be callable by whoever the policy is evaluated
    // for, which is the querying role.
    `GRANT EXECUTE ON FUNCTION ${QUALIFIED_TENANT_CONTEXT_FUNCTION}() TO "${runtime}", "${authPlane}", "${ddl}";`,
    `GRANT EXECUTE ON FUNCTION ${QUALIFIED_AUTH_PLANE_FUNCTION}(text) TO "${runtime}", "${authPlane}", "${ddl}";`,
    `GRANT EXECUTE ON FUNCTION ${QUALIFIED_AUTH_PLANE_ROW_FUNCTION}(uuid, text) TO "${runtime}", "${authPlane}", "${ddl}";`,
  );

  // --- 5. control-plane denial --------------------------------------------
  for (const table of RUNTIME_DENIED_TABLES) {
    assertSafeIdent('denied table', table);
    statements.push(`REVOKE ALL ON TABLE "${table}" FROM "${runtime}";`);
  }
  // G2 review carry-forward finding 6: ledger history is append-only by
  // trigger. A trigger can be disabled by whoever owns the table, so the
  // runtime additionally holds no UPDATE/DELETE grant on it at all.
  statements.push(
    `REVOKE UPDATE, DELETE ON TABLE "tenant_migration_ledger_history" FROM "${runtime}";`,
    `REVOKE UPDATE, DELETE ON TABLE "tenant_migration_ledger" FROM "${runtime}";`,
  );

  // --- 6. auth-plane privileges -------------------------------------------
  // SELECT only, and only on the credential index and its joins. The auth plane
  // cannot write anything; child-key creation crosses the boundary through the
  // DDL-owned service path, not through this role.
  for (const table of AUTH_PLANE_TABLES) {
    assertSafeIdent('auth-plane table', table);
    statements.push(`GRANT SELECT ON TABLE "${table}" TO "${authPlane}";`);
  }

  // --- 7. legacy cutover role ----------------------------------------------
  // `packages/cli/src/lib/role-cutover.ts` provisions ONE scoped role
  // (`pgserve_omni_<fp>_role`) and hands it `GRANT SELECT, INSERT, UPDATE,
  // DELETE ON ALL TABLES IN SCHEMA public` plus default privileges. Section 2
  // moves every OBJECT it owns to the DDL role, but ownership is not privilege:
  // without this section the pre-cutover role keeps its blanket grants and can
  // still SELECT `auth_credentials.key_hash` — the one table that is RLS-free by
  // design and therefore protected by privilege alone (ADR-0003).
  //
  // Placed last, after every GRANT above, because `GRANT ... ON ALL TABLES`
  // would otherwise re-add what this revokes. Guarded on role existence: REVOKE
  // against a role that was never provisioned is a hard error, and a deployment
  // that never ran the CLI cutover must still be able to apply this plan.
  for (const legacy of legacyRoles) {
    if (legacy === ddl || legacy === runtime || legacy === authPlane || legacy === authPlaneMarker) {
      throw new Error(`tenancy-roles: legacy role ${JSON.stringify(legacy)} collides with a provisioned identity`);
    }
    statements.push(legacyRevokeStatement(legacy, database), revokeMembership(authPlaneMarker, legacy));
  }

  return statements;
}

/**
 * Strip every privilege the CLI cutover granted a legacy scoped role.
 *
 * Wrapped in one `DO` block guarded on `pg_roles`, so the whole thing is a
 * no-op on a deployment where that role never existed. `ALTER DEFAULT
 * PRIVILEGES` is issued twice on purpose: once `FOR ROLE` the legacy role
 * (the grants it made for itself) and once for the current provisioner
 * identity (the grants the cutover script made as superuser) — a default
 * privilege survives an object-level REVOKE and would silently re-arm the
 * legacy role on the next table created.
 */
function legacyRevokeStatement(legacy: string, database: string): string {
  const revokes = [
    'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM %I',
    'REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM %I',
    'REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM %I',
    'REVOKE ALL PRIVILEGES ON SCHEMA public FROM %I',
    'REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA drizzle FROM %I',
    'REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA drizzle FROM %I',
    'REVOKE ALL PRIVILEGES ON SCHEMA drizzle FROM %I',
    `REVOKE ALL PRIVILEGES ON DATABASE "${database}" FROM %I`,
    'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public REVOKE ALL ON TABLES FROM %I',
    'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I',
    'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA drizzle REVOKE ALL ON TABLES FROM %I',
    'ALTER DEFAULT PRIVILEGES FOR ROLE %I IN SCHEMA drizzle REVOKE ALL ON SEQUENCES FROM %I',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA drizzle REVOKE ALL ON TABLES FROM %I',
    'ALTER DEFAULT PRIVILEGES IN SCHEMA drizzle REVOKE ALL ON SEQUENCES FROM %I',
  ]
    .map((template) => {
      const args = Array.from({ length: (template.match(/%I/g) ?? []).length }, () => `'${legacy}'`).join(', ');
      return `    EXECUTE format(${quoteLiteral(template)}, ${args});`;
    })
    .join('\n');

  return `DO $omni$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${legacy}') THEN
${revokes}
  END IF;
END
$omni$;`;
}

/** Apply {@link roleProvisioningStatements} on a provisioner (superuser) connection. */
export async function applyTenancyRoles(
  db: Database,
  passwords: TenancyRolePasswords,
  roles: TenancyRoleNames = DEFAULT_ROLE_NAMES,
  database = 'omni',
  legacyRoles: readonly string[] = [],
): Promise<number> {
  const statements = roleProvisioningStatements(passwords, roles, database, legacyRoles);
  for (const statement of statements) {
    await db.execute(sql.raw(statement));
  }
  return statements.length;
}

// ---------------------------------------------------------------------------
// Probes
// ---------------------------------------------------------------------------

export interface RoleAttributes {
  readonly name: string;
  readonly superuser: boolean;
  readonly bypassRls: boolean;
  readonly createDb: boolean;
  readonly createRole: boolean;
  readonly replication: boolean;
  readonly canLogin: boolean;
}

export async function readRoleAttributes(db: Database, name: string): Promise<RoleAttributes | null> {
  const rows = (await db.execute(sql`
    SELECT rolname::text AS name, rolsuper, rolbypassrls, rolcreatedb, rolcreaterole, rolreplication, rolcanlogin
    FROM pg_roles WHERE rolname = ${name}
  `)) as unknown as {
    name: string;
    rolsuper: boolean;
    rolbypassrls: boolean;
    rolcreatedb: boolean;
    rolcreaterole: boolean;
    rolreplication: boolean;
    rolcanlogin: boolean;
  }[];
  const row = rows[0];
  if (!row) return null;
  return {
    name: row.name,
    superuser: row.rolsuper,
    bypassRls: row.rolbypassrls,
    createDb: row.rolcreatedb,
    createRole: row.rolcreaterole,
    replication: row.rolreplication,
    canLogin: row.rolcanlogin,
  };
}

/** The exact ADR-0004 attribute contract, as a reusable assertion. */
export function roleAttributeViolations(attributes: RoleAttributes): string[] {
  const violations: string[] = [];
  if (attributes.superuser) violations.push('role is SUPERUSER');
  if (attributes.bypassRls) violations.push('role is BYPASSRLS');
  if (attributes.createDb) violations.push('role is CREATEDB');
  if (attributes.createRole) violations.push('role is CREATEROLE');
  if (attributes.replication) violations.push('role is REPLICATION');
  return violations;
}

/** `REVOKE <group> FROM <member>`, but only when the membership actually exists. */
function revokeMembership(group: string, member: string): string {
  return `DO $omni$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_auth_members m
    JOIN pg_roles g ON g.oid = m.roleid
    JOIN pg_roles r ON r.oid = m.member
    WHERE g.rolname = '${group}' AND r.rolname = '${member}'
  ) THEN
    EXECUTE 'REVOKE "${group}" FROM "${member}"';
  END IF;
END
$omni$;`;
}

function quoteLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}
