apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omni.fullname" . }}-config
  labels:
    {{- include "omni.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- range $k, $v := .Values.extraConfig }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  NATS_URL: {{ include "omni.natsUrl" . | quote }}
