# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class GetAutomationLogs200ResponseItemsInner(BaseModel):
    """
    GetAutomationLogs200ResponseItemsInner
    """ # noqa: E501
    id: UUID = Field(description="Log UUID")
    automation_id: UUID = Field(description="Automation UUID", alias="automationId")
    event_id: UUID = Field(description="Event UUID", alias="eventId")
    event_type: StrictStr = Field(description="Event type", alias="eventType")
    status: StrictStr = Field(description="Execution status")
    error: Optional[StrictStr] = Field(description="Error message")
    executed_at: datetime = Field(description="Execution timestamp", alias="executedAt")
    duration_ms: StrictInt = Field(description="Duration (ms)", alias="durationMs")
    __properties: ClassVar[List[str]] = ["id", "automationId", "eventId", "eventType", "status", "error", "executedAt", "durationMs"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['success', 'failed', 'skipped']):
            raise ValueError("must be one of enum values ('success', 'failed', 'skipped')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAutomationLogs200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAutomationLogs200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "automationId": obj.get("automationId"),
            "eventId": obj.get("eventId"),
            "eventType": obj.get("eventType"),
            "status": obj.get("status"),
            "error": obj.get("error"),
            "executedAt": obj.get("executedAt"),
            "durationMs": obj.get("durationMs")
        })
        return _obj


