# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class Instance(BaseModel):
    """
    Instance
    """ # noqa: E501
    id: UUID = Field(description="Instance UUID")
    name: StrictStr = Field(description="Instance name")
    channel: StrictStr = Field(description="Channel type")
    is_active: StrictBool = Field(description="Whether instance is active", alias="isActive")
    is_default: StrictBool = Field(description="Whether this is the default instance for channel", alias="isDefault")
    profile_name: Optional[StrictStr] = Field(description="Connected profile name", alias="profileName")
    profile_pic_url: Optional[StrictStr] = Field(description="Profile picture URL", alias="profilePicUrl")
    owner_identifier: Optional[StrictStr] = Field(description="Owner identifier", alias="ownerIdentifier")
    agent_provider_id: Optional[UUID] = Field(description="Agent provider UUID", alias="agentProviderId")
    agent_id: Optional[StrictStr] = Field(description="Agent ID", alias="agentId")
    agent_timeout: Union[StrictFloat, StrictInt] = Field(description="Agent timeout in seconds", alias="agentTimeout")
    agent_stream_mode: StrictBool = Field(description="Whether streaming is enabled", alias="agentStreamMode")
    created_at: datetime = Field(description="Creation timestamp", alias="createdAt")
    updated_at: datetime = Field(description="Last update timestamp", alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "name", "channel", "isActive", "isDefault", "profileName", "profilePicUrl", "ownerIdentifier", "agentProviderId", "agentId", "agentTimeout", "agentStreamMode", "createdAt", "updatedAt"]

    @field_validator('channel')
    def channel_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['whatsapp-baileys', 'whatsapp-cloud', 'discord', 'slack', 'telegram']):
            raise ValueError("must be one of enum values ('whatsapp-baileys', 'whatsapp-cloud', 'discord', 'slack', 'telegram')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Instance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if profile_name (nullable) is None
        # and model_fields_set contains the field
        if self.profile_name is None and "profile_name" in self.model_fields_set:
            _dict['profileName'] = None

        # set to None if profile_pic_url (nullable) is None
        # and model_fields_set contains the field
        if self.profile_pic_url is None and "profile_pic_url" in self.model_fields_set:
            _dict['profilePicUrl'] = None

        # set to None if owner_identifier (nullable) is None
        # and model_fields_set contains the field
        if self.owner_identifier is None and "owner_identifier" in self.model_fields_set:
            _dict['ownerIdentifier'] = None

        # set to None if agent_provider_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_provider_id is None and "agent_provider_id" in self.model_fields_set:
            _dict['agentProviderId'] = None

        # set to None if agent_id (nullable) is None
        # and model_fields_set contains the field
        if self.agent_id is None and "agent_id" in self.model_fields_set:
            _dict['agentId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Instance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "channel": obj.get("channel"),
            "isActive": obj.get("isActive"),
            "isDefault": obj.get("isDefault"),
            "profileName": obj.get("profileName"),
            "profilePicUrl": obj.get("profilePicUrl"),
            "ownerIdentifier": obj.get("ownerIdentifier"),
            "agentProviderId": obj.get("agentProviderId"),
            "agentId": obj.get("agentId"),
            "agentTimeout": obj.get("agentTimeout"),
            "agentStreamMode": obj.get("agentStreamMode"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


