# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class ListDeadLetters200ResponseItemsInner(BaseModel):
    """
    ListDeadLetters200ResponseItemsInner
    """ # noqa: E501
    id: UUID = Field(description="Dead letter UUID")
    event_id: UUID = Field(description="Original event UUID", alias="eventId")
    event_type: StrictStr = Field(description="Event type", alias="eventType")
    status: StrictStr = Field(description="Status")
    error_message: StrictStr = Field(description="Error message", alias="errorMessage")
    error_stack: Optional[StrictStr] = Field(description="Error stack trace", alias="errorStack")
    retry_count: StrictInt = Field(description="Retry attempts", alias="retryCount")
    last_retry_at: Optional[datetime] = Field(description="Last retry timestamp", alias="lastRetryAt")
    resolved_at: Optional[datetime] = Field(description="Resolution timestamp", alias="resolvedAt")
    resolution_note: Optional[StrictStr] = Field(description="Resolution note", alias="resolutionNote")
    created_at: datetime = Field(description="Creation timestamp", alias="createdAt")
    __properties: ClassVar[List[str]] = ["id", "eventId", "eventType", "status", "errorMessage", "errorStack", "retryCount", "lastRetryAt", "resolvedAt", "resolutionNote", "createdAt"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'retrying', 'resolved', 'abandoned']):
            raise ValueError("must be one of enum values ('pending', 'retrying', 'resolved', 'abandoned')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListDeadLetters200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if error_stack (nullable) is None
        # and model_fields_set contains the field
        if self.error_stack is None and "error_stack" in self.model_fields_set:
            _dict['errorStack'] = None

        # set to None if last_retry_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_retry_at is None and "last_retry_at" in self.model_fields_set:
            _dict['lastRetryAt'] = None

        # set to None if resolved_at (nullable) is None
        # and model_fields_set contains the field
        if self.resolved_at is None and "resolved_at" in self.model_fields_set:
            _dict['resolvedAt'] = None

        # set to None if resolution_note (nullable) is None
        # and model_fields_set contains the field
        if self.resolution_note is None and "resolution_note" in self.model_fields_set:
            _dict['resolutionNote'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListDeadLetters200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "eventId": obj.get("eventId"),
            "eventType": obj.get("eventType"),
            "status": obj.get("status"),
            "errorMessage": obj.get("errorMessage"),
            "errorStack": obj.get("errorStack"),
            "retryCount": obj.get("retryCount"),
            "lastRetryAt": obj.get("lastRetryAt"),
            "resolvedAt": obj.get("resolvedAt"),
            "resolutionNote": obj.get("resolutionNote"),
            "createdAt": obj.get("createdAt")
        })
        return _obj


