# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class ListInstanceGroups200ResponseItemsInner(BaseModel):
    """
    ListInstanceGroups200ResponseItemsInner
    """ # noqa: E501
    external_id: StrictStr = Field(description="External group ID", alias="externalId")
    name: Optional[StrictStr] = Field(default=None, description="Group name")
    description: Optional[StrictStr] = Field(default=None, description="Group description")
    member_count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number of members", alias="memberCount")
    created_at: Optional[datetime] = Field(default=None, description="Creation timestamp", alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, description="Creator ID", alias="createdBy")
    is_read_only: Optional[StrictBool] = Field(default=None, description="Whether group is read-only", alias="isReadOnly")
    platform_metadata: Optional[Dict[str, Any]] = Field(default=None, description="Platform-specific metadata", alias="platformMetadata")
    __properties: ClassVar[List[str]] = ["externalId", "name", "description", "memberCount", "createdAt", "createdBy", "isReadOnly", "platformMetadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListInstanceGroups200ResponseItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListInstanceGroups200ResponseItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "externalId": obj.get("externalId"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "memberCount": obj.get("memberCount"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "isReadOnly": obj.get("isReadOnly"),
            "platformMetadata": obj.get("platformMetadata")
        })
        return _obj


