# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from .list_automations200_response_items_inner_actions_inner_any_of import ListAutomations200ResponseItemsInnerActionsInnerAnyOf
from .list_automations200_response_items_inner_actions_inner_any_of1 import ListAutomations200ResponseItemsInnerActionsInnerAnyOf1
from .list_automations200_response_items_inner_actions_inner_any_of2 import ListAutomations200ResponseItemsInnerActionsInnerAnyOf2
from .list_automations200_response_items_inner_actions_inner_any_of3 import ListAutomations200ResponseItemsInnerActionsInnerAnyOf3
from .list_automations200_response_items_inner_actions_inner_any_of4 import ListAutomations200ResponseItemsInnerActionsInnerAnyOf4
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

LISTAUTOMATIONS200RESPONSEITEMSINNERACTIONSINNER_ANY_OF_SCHEMAS = ["ListAutomations200ResponseItemsInnerActionsInnerAnyOf", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf1", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf2", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf3", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf4"]

class ListAutomations200ResponseItemsInnerActionsInner(BaseModel):
    """
    ListAutomations200ResponseItemsInnerActionsInner
    """

    # data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf
    anyof_schema_1_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf] = None
    # data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf1
    anyof_schema_2_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf1] = None
    # data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf2
    anyof_schema_3_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf2] = None
    # data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf3
    anyof_schema_4_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf3] = None
    # data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf4
    anyof_schema_5_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf4] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[ListAutomations200ResponseItemsInnerActionsInnerAnyOf, ListAutomations200ResponseItemsInnerActionsInnerAnyOf1, ListAutomations200ResponseItemsInnerActionsInnerAnyOf2, ListAutomations200ResponseItemsInnerActionsInnerAnyOf3, ListAutomations200ResponseItemsInnerActionsInnerAnyOf4]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "ListAutomations200ResponseItemsInnerActionsInnerAnyOf", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf1", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf2", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf3", "ListAutomations200ResponseItemsInnerActionsInnerAnyOf4" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = ListAutomations200ResponseItemsInnerActionsInner.model_construct()
        error_messages = []
        # validate data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf
        if not isinstance(v, ListAutomations200ResponseItemsInnerActionsInnerAnyOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListAutomations200ResponseItemsInnerActionsInnerAnyOf`")
        else:
            return v

        # validate data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf1
        if not isinstance(v, ListAutomations200ResponseItemsInnerActionsInnerAnyOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListAutomations200ResponseItemsInnerActionsInnerAnyOf1`")
        else:
            return v

        # validate data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf2
        if not isinstance(v, ListAutomations200ResponseItemsInnerActionsInnerAnyOf2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListAutomations200ResponseItemsInnerActionsInnerAnyOf2`")
        else:
            return v

        # validate data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf3
        if not isinstance(v, ListAutomations200ResponseItemsInnerActionsInnerAnyOf3):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListAutomations200ResponseItemsInnerActionsInnerAnyOf3`")
        else:
            return v

        # validate data type: ListAutomations200ResponseItemsInnerActionsInnerAnyOf4
        if not isinstance(v, ListAutomations200ResponseItemsInnerActionsInnerAnyOf4):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ListAutomations200ResponseItemsInnerActionsInnerAnyOf4`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in ListAutomations200ResponseItemsInnerActionsInner with anyOf schemas: ListAutomations200ResponseItemsInnerActionsInnerAnyOf, ListAutomations200ResponseItemsInnerActionsInnerAnyOf1, ListAutomations200ResponseItemsInnerActionsInnerAnyOf2, ListAutomations200ResponseItemsInnerActionsInnerAnyOf3, ListAutomations200ResponseItemsInnerActionsInnerAnyOf4. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf] = None
        try:
            instance.actual_instance = ListAutomations200ResponseItemsInnerActionsInnerAnyOf.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf1] = None
        try:
            instance.actual_instance = ListAutomations200ResponseItemsInnerActionsInnerAnyOf1.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_3_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf2] = None
        try:
            instance.actual_instance = ListAutomations200ResponseItemsInnerActionsInnerAnyOf2.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_4_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf3] = None
        try:
            instance.actual_instance = ListAutomations200ResponseItemsInnerActionsInnerAnyOf3.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_5_validator: Optional[ListAutomations200ResponseItemsInnerActionsInnerAnyOf4] = None
        try:
            instance.actual_instance = ListAutomations200ResponseItemsInnerActionsInnerAnyOf4.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ListAutomations200ResponseItemsInnerActionsInner with anyOf schemas: ListAutomations200ResponseItemsInnerActionsInnerAnyOf, ListAutomations200ResponseItemsInnerActionsInnerAnyOf1, ListAutomations200ResponseItemsInnerActionsInnerAnyOf2, ListAutomations200ResponseItemsInnerActionsInnerAnyOf3, ListAutomations200ResponseItemsInnerActionsInnerAnyOf4. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], ListAutomations200ResponseItemsInnerActionsInnerAnyOf, ListAutomations200ResponseItemsInnerActionsInnerAnyOf1, ListAutomations200ResponseItemsInnerActionsInnerAnyOf2, ListAutomations200ResponseItemsInnerActionsInnerAnyOf3, ListAutomations200ResponseItemsInnerActionsInnerAnyOf4]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


