# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from omni_generated.models.list_automations200_response_items_inner_actions_inner import ListAutomations200ResponseItemsInnerActionsInner
from omni_generated.models.test_automation200_response_condition_results_inner import TestAutomation200ResponseConditionResultsInner
from typing import Optional, Set
from typing_extensions import Self

class TestAutomation200Response(BaseModel):
    """
    TestAutomation200Response
    """ # noqa: E501
    matched: StrictBool
    condition_results: Optional[List[TestAutomation200ResponseConditionResultsInner]] = Field(default=None, alias="conditionResults")
    would_execute: Optional[List[ListAutomations200ResponseItemsInnerActionsInner]] = Field(default=None, alias="wouldExecute")
    __properties: ClassVar[List[str]] = ["matched", "conditionResults", "wouldExecute"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TestAutomation200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in condition_results (list)
        _items = []
        if self.condition_results:
            for _item_condition_results in self.condition_results:
                if _item_condition_results:
                    _items.append(_item_condition_results.to_dict())
            _dict['conditionResults'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in would_execute (list)
        _items = []
        if self.would_execute:
            for _item_would_execute in self.would_execute:
                if _item_would_execute:
                    _items.append(_item_would_execute.to_dict())
            _dict['wouldExecute'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TestAutomation200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "matched": obj.get("matched"),
            "conditionResults": [TestAutomation200ResponseConditionResultsInner.from_dict(_item) for _item in obj["conditionResults"]] if obj.get("conditionResults") is not None else None,
            "wouldExecute": [ListAutomations200ResponseItemsInnerActionsInner.from_dict(_item) for _item in obj["wouldExecute"]] if obj.get("wouldExecute") is not None else None
        })
        return _obj


