# coding: utf-8

"""
    Omni v2 API

    Omni v2 is a universal event-driven omnichannel platform API.  ## Authentication  All API requests require an API key passed via the `x-api-key` header:  ``` x-api-key: omni_sk_your_key_here ```  ## Rate Limiting  - Messages: 60 requests/minute - Events: 100 requests/minute - Instances: 30 requests/minute - General: 1000 requests/minute  Rate limit headers are included in responses: - `X-RateLimit-Limit`: Max requests per window - `X-RateLimit-Remaining`: Requests remaining - `X-RateLimit-Reset`: Unix timestamp when limit resets  ## Pagination  List endpoints use cursor-based pagination:  ``` GET /api/v2/events?limit=50&cursor=abc123 ```  Response includes `meta.hasMore` and `meta.cursor` for next page.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from .create_automation_request_debounce import CreateAutomationRequestDebounce
from .list_automations200_response_items_inner_actions_inner import ListAutomations200ResponseItemsInnerActionsInner
from .list_automations200_response_items_inner_trigger_conditions_inner import ListAutomations200ResponseItemsInnerTriggerConditionsInner
from typing import Optional, Set
from typing_extensions import Self

class UpdateAutomationRequest(BaseModel):
    """
    UpdateAutomationRequest
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = Field(default=None, description="Name")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    trigger_event_type: Optional[Annotated[str, Field(min_length=1, strict=True)]] = Field(default=None, description="Trigger event type", alias="triggerEventType")
    trigger_conditions: Optional[List[ListAutomations200ResponseItemsInnerTriggerConditionsInner]] = Field(default=None, description="Conditions", alias="triggerConditions")
    condition_logic: Optional[StrictStr] = Field(default='and', description="Condition logic: \"and\" (all must match) or \"or\" (any must match)", alias="conditionLogic")
    actions: Optional[Annotated[List[ListAutomations200ResponseItemsInnerActionsInner], Field(min_length=1)]] = Field(default=None, description="Actions")
    debounce: Optional[CreateAutomationRequestDebounce] = None
    enabled: Optional[StrictBool] = Field(default=True, description="Whether enabled")
    priority: Optional[StrictInt] = Field(default=0, description="Priority")
    __properties: ClassVar[List[str]] = ["name", "description", "triggerEventType", "triggerConditions", "conditionLogic", "actions", "debounce", "enabled", "priority"]

    @field_validator('condition_logic')
    def condition_logic_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['and', 'or']):
            raise ValueError("must be one of enum values ('and', 'or')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateAutomationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in trigger_conditions (list)
        _items = []
        if self.trigger_conditions:
            for _item_trigger_conditions in self.trigger_conditions:
                if _item_trigger_conditions:
                    _items.append(_item_trigger_conditions.to_dict())
            _dict['triggerConditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of debounce
        if self.debounce:
            _dict['debounce'] = self.debounce.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateAutomationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "triggerEventType": obj.get("triggerEventType"),
            "triggerConditions": [ListAutomations200ResponseItemsInnerTriggerConditionsInner.from_dict(_item) for _item in obj["triggerConditions"]] if obj.get("triggerConditions") is not None else None,
            "conditionLogic": obj.get("conditionLogic") if obj.get("conditionLogic") is not None else 'and',
            "actions": [ListAutomations200ResponseItemsInnerActionsInner.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "debounce": CreateAutomationRequestDebounce.from_dict(obj["debounce"]) if obj.get("debounce") is not None else None,
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "priority": obj.get("priority") if obj.get("priority") is not None else 0
        })
        return _obj


