/**
 * Typed access to the last evidence run's per-family summary. This small file is
 * regenerated by `scripts/run-evidence.ts` (`bun run evidence`) and is safe to
 * commit: it holds only timestamps, ok flags, and check counts — never keys or
 * message content. The full evidence lives (git-committed, pack-excluded) under
 * `apps/khal-ui/evidence/evidence-<date>.json`.
 */
import summary from './evidence-summary.json' with { type: 'json' };

export interface EvidenceFamily {
  /** ISO timestamp of when this family's validator last ran, or null if never. */
  ranAt: string | null;
  /** Whether the last run passed (null if never run). */
  ok: boolean | null;
  /** Number of checks the validator recorded. */
  checks: number;
  /** Optional caveat (e.g. chat's canary-budget note). */
  note?: string;
}

export interface EvidenceSummary {
  $tool: string;
  generatedAt: string | null;
  backendVersion: string | null;
  families: Record<'instances' | 'agents' | 'coverage' | 'chat', EvidenceFamily>;
}

export const evidenceSummary = summary as EvidenceSummary;
